### ISSUE TITLE
Database standard number of fields and type of data setting...

### ISSUE THREAD

**Issue by runtimevic** [Beckhoff-USA-Community/TE2000_TcHMI_AdvancedServerExtension#2]
It could be done in some way that was more standard, 
that you could configure the number of fields by which the database is formed and what types of data is each field, so it would be valid for any database regardless of the number of fields and type of data of the field. That it could be configured just like the database connection and the database name...
thanks You.

**Comment by ZDaulton** [comment]
The sample extension is meant to show how to use the TcHmi Server Extension SDK to make symbol methods and connections to an external database. You can use this project as an example for how to implement your own database interface with TcHmi. I would suggest adding a new method "CreateDatabase" where a user could define a new database and submit it. 

One thing to be careful of would be SQL Injection with any kind of method that allows open ended commands. Validating commands at the server end would be needed.
