### ISSUE TITLE
Error on extension activation

### ISSUE THREAD

**Issue by FabBag72** [Beckhoff-USA-Community/TE2000_TcHMI_AdvancedServerExtension#3]
Hi Zachary, I'd like to open your project by VS2019 16.11.19 and TcHMI 1.12.760.48. If I Rebuild C# project I get this messages in Output window:

Rebuild started...
1>------ Rebuild All started: Project: SQLiteConnector, Configuration: Debug Any CPU ------
Restored C:\TE2000_TcHMI_AdvancedServerExtension-master\SQLiteConnector\SQLiteConnector.csproj (in 90 ms).
1>C:\TE2000_TcHMI_AdvancedServerExtension-master\SQLiteConnector\SQLiteConnector.csproj : warning MSB4011: "C:\Program Files\dotnet\sdk\5.0.416\Sdks\Microsoft.NET.Sdk\Sdk\Sdk.targets" cannot be imported again. It was already imported at "C:\TE2000_TcHMI_AdvancedServerExtension-master\SQLiteConnector\SQLiteConnector.csproj (13,3)". This is most likely a build authoring error. This subsequent import will be ignored.
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2203,5): warning MSB3277: Found conflicts between different versions of "System.Text.Json" that could not be resolved.
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2203,5): warning MSB3277: There was a conflict between "System.Text.Json, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51" and "System.Text.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51".
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2203,5): warning MSB3277:     "System.Text.Json, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51" was chosen because it was primary and "System.Text.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51" was not.
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2203,5): warning MSB3277:     References which depend on "System.Text.Json, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51" [C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\3.1.0\ref\netcoreapp3.1\System.Text.Json.dll].
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2203,5): warning MSB3277:         C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\3.1.0\ref\netcoreapp3.1\System.Text.Json.dll
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2203,5): warning MSB3277:           Project file item includes which caused reference "C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\3.1.0\ref\netcoreapp3.1\System.Text.Json.dll".
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2203,5): warning MSB3277:             C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\3.1.0\ref\netcoreapp3.1\System.Text.Json.dll
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2203,5): warning MSB3277:     References which depend on "System.Text.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51" [].
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2203,5): warning MSB3277:         C:\TwinCAT\Functions\TE2000-HMI-Engineering\Infrastructure\TcHmiServer\Latest\win-x64\API\2.1.0.0\TcHmiSrvExtNet.Core.dll
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2203,5): warning MSB3277:           Project file item includes which caused reference "C:\TwinCAT\Functions\TE2000-HMI-Engineering\Infrastructure\TcHmiServer\Latest\win-x64\API\2.1.0.0\TcHmiSrvExtNet.Core.dll".
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2203,5): warning MSB3277:             TcHmiSrvExtNet.Core
1>C:\TE2000_TcHMI_AdvancedServerExtension-master\SQLiteConnector\SQLiteConnector.cs(141,30,141,32): warning CS0168: The variable 'ex' is declared but never used
1>SQLiteConnector -> C:\TE2000_TcHMI_AdvancedServerExtension-master\SQLiteConnector\bin\Debug\win10-x64\SQLiteConnector.dll
1>C:\TE2000_TcHMI_AdvancedServerExtension-master\SQLiteConnector\config\ExtensionSettings.Schema.json
1>C:\TE2000_TcHMI_AdvancedServerExtension-master\SQLiteConnector\config\Language.Schema.json
1>C:\TE2000_TcHMI_AdvancedServerExtension-master\SQLiteConnector\config\SQLiteConnector.Config.json
1>C:\TE2000_TcHMI_AdvancedServerExtension-master\SQLiteConnector\config\SQLiteConnector.Language.en.json
1>C:\TE2000_TcHMI_AdvancedServerExtension-master\SQLiteConnector\config\SQLiteConnector.Schema.json
1>5 File(s) copied
1>Done building project "SQLiteConnector.csproj".
========== Rebuild All: 1 succeeded, 0 failed, 0 skipped ==========

Further, If I try to enable SQLiteConnector server extension (because it has red arrow), I get this errors and warnings in Error List window:

Severity	Code	Description	Project	File	Line	Suppression State
Warning	MSB3277	Found conflicts between different versions of "System.Text.Json" that could not be resolved.
There was a conflict between "System.Text.Json, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51" and "System.Text.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51".
    "System.Text.Json, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51" was chosen because it was primary and "System.Text.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51" was not.
    References which depend on "System.Text.Json, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51" [C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\3.1.0\ref\netcoreapp3.1\System.Text.Json.dll].
        C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\3.1.0\ref\netcoreapp3.1\System.Text.Json.dll
          Project file item includes which caused reference "C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\3.1.0\ref\netcoreapp3.1\System.Text.Json.dll".
            C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\3.1.0\ref\netcoreapp3.1\System.Text.Json.dll
    References which depend on "System.Text.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51" [].
        C:\TwinCAT\Functions\TE2000-HMI-Engineering\Infrastructure\TcHmiServer\Latest\win-x64\API\2.1.0.0\TcHmiSrvExtNet.Core.dll
          Project file item includes which caused reference "C:\TwinCAT\Functions\TE2000-HMI-Engineering\Infrastructure\TcHmiServer\Latest\win-x64\API\2.1.0.0\TcHmiSrvExtNet.Core.dll".
            TcHmiSrvExtNet.Core	SQLiteConnector	C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets	2203	
Warning	MSB4011	"C:\Program Files\dotnet\sdk\5.0.416\Sdks\Microsoft.NET.Sdk\Sdk\Sdk.targets" cannot be imported again. It was already imported at "C:\TE2000_TcHMI_AdvancedServerExtension-master\SQLiteConnector\SQLiteConnector.csproj (13,3)". This is most likely a build authoring error. This subsequent import will be ignored. 	SQLiteConnector		1	
Warning	CS0168	The variable 'ex' is declared but never used	SQLiteConnector	C:\TE2000_TcHMI_AdvancedServerExtension-master\SQLiteConnector\SQLiteConnector.cs	141	Active
Error		FILE_NOT_FOUND error: C:\TE2000_TcHMI_AdvancedServerExtension-master\.engineering_servers\TcHmiDatabaseConnect_Dev\TcHmiExtensionContainer.Core.5532.SQLiteConnector.log	TcHmiDatabaseConnect_Dev	C:\TE2000_TcHMI_AdvancedServerExtension-master\TcHmiDatabaseConnect_Dev\TcHmiDatabaseConnect_Dev.hmiproj	2	
Error		TwinCAT HMI Server: [EE TcHmiSrv] Failed to load extension 'SQLiteConnector' because .NET Core Runtime 6.0.0 or later could not be found.	TcHmiDatabaseConnect_Dev	C:\TE2000_TcHMI_AdvancedServerExtension-master\TcHmiDatabaseConnect_Dev\TcHmiDatabaseConnect_Dev.hmiproj	2	
Error		TwinCAT HMI Server: [EE TcHmiSrv] Failed to load extension 'SQLiteConnector' because .NET Core Desktop Runtime 6.0.0 or later could not be found.	TcHmiDatabaseConnect_Dev	C:\TE2000_TcHMI_AdvancedServerExtension-master\TcHmiDatabaseConnect_Dev\TcHmiDatabaseConnect_Dev.hmiproj	2	
Error		TwinCAT HMI Server: [EE TcHmiSrv] Asynchronous config handler returned an error for symbol 'EXTENSIONS::SQLiteConnector' with request ID 61,902.00 in domain 'TcHmiSrv': File not found (C:\TE2000_TcHMI_AdvancedServerExtension-master\.engineering_servers\TcHmiDatabaseConnect_Dev\TcHmiExtensionContainer.Core.5532.SQLiteConnector.log)	TcHmiDatabaseConnect_Dev	C:\TE2000_TcHMI_AdvancedServerExtension-master\TcHmiDatabaseConnect_Dev\TcHmiDatabaseConnect_Dev.hmiproj	2	

Do you have any suggestion about it?

BR

Fabrizio Bagnara

**Comment by FabBag72** [comment]
Ops... and what if I installed .NET 6 SDK? Maybe it is better!! Now, everything is working. Bye.

**Comment by ZDaulton** [comment]
@FabBag72 We use a rollforward policy with the extension container runtime environments. These needs to be configured directly on the runtime system for Core extensions. Normal extensions should automatically be .NET 4.8

Typically located here:
C:\TwinCAT\Functions\TF2000-HMI-Server\TcHmiExtensionContainer.Core.runtimeconfig.json
